"""Add contact phone to Product model

Revision ID: 149241eb37ab
Revises: 
Create Date: 2025-10-31 17:03:02.234045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149241eb37ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('contact_phone')

    # ### end Alembic commands ###
